apiVersion: batch/v1
kind: CronJob
metadata:
  name: helloworld-cronjob-1
spec:
  # Runs every minute
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            command: ["echo", "Hi Anand - Cron Job"]
          restartPolicy: Never