apiVersion: apps/v1 
kind: Deployment
metadata:
  name: my-nginx
  labels: 
    app: my-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx:1.20
        ports:
        - containerPort: 80        
        command: ["sh", "-c"]
        args:
        - while true; do
            echo "$(date) some data" >> /var/log/my-app.log;
            sleep 1;
          done;
        volumeMounts:
        - name: log-data
          mountPath: "/var/log"

      - name: log-sidecar
        image: busybox:1.28
        command: ["sh", "-c"]
        args:
        - tail -f /var/sidecar/my-app.log;
        volumeMounts:
        - name: log-data
          mountPath: "/var/sidecar"        

      volumes:
      - name: log-data
        emptyDir: {}
