apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld-6
spec:
  parallelism: 3
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "60"]
      restartPolicy: Never