apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld-7
spec:
  completions: 5
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "60"]
      restartPolicy: Never