apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld-8
spec:
  suspend: true
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "60"]
      restartPolicy: Never